# Generated by Django 5.2.7 on 2025-10-28 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('GENERAL_MEDICINE', 'Medicina General'), ('CARDIOLOGY', 'Cardiología'), ('PEDIATRICS', 'Pediatría'), ('DERMATOLOGY', 'Dermatología'), ('NEUROLOGY', 'Neurología'), ('ORTHOPEDICS', 'Traumatología')], max_length=50)),
                ('experience', models.CharField(max_length=100)),
                ('next_available_slot', models.DateTimeField()),
                ('price_per_consultation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.URLField(blank=True)),
                ('is_telehealth_available', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=150)),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('consultation_type', models.CharField(choices=[('IN_PERSON', 'Presencial'), ('TELEHEALTH', 'Teleconsulta')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada')], default='CONFIRMED', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time_slots', to='api.doctor')),
            ],
        ),
    ]
